# Generated by Django 5.2.7 on 2026-06-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_message_text_content_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='path',
            new_name='file',
        ),
    ]
